repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
      # - id: go-vet
      - id: go-mod-tidy
      - id: go-test-mod
        args: [-v]
